name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pyelectroluxgroup
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      run: poetry install --sync --no-interaction
    - name: Package project
      run: poetry build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
